// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	ConfigRequest
	ConfigResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Challenge int32

const (
	Challenge_TOKEN   Challenge = 0
	Challenge_AWS_KMS Challenge = 1
	Challenge_GC_KMS  Challenge = 2
)

var Challenge_name = map[int32]string{
	0: "TOKEN",
	1: "AWS_KMS",
	2: "GC_KMS",
}
var Challenge_value = map[string]int32{
	"TOKEN":   0,
	"AWS_KMS": 1,
	"GC_KMS":  2,
}

func (x Challenge) String() string {
	return proto.EnumName(Challenge_name, int32(x))
}
func (Challenge) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Action int32

const (
	Action_INIT               Action = 0
	Action_CHALLENGE          Action = 1
	Action_CHALLENGE_RESPONSE Action = 2
	Action_PAYLOAD            Action = 3
	Action_FAIL               Action = 4
)

var Action_name = map[int32]string{
	0: "INIT",
	1: "CHALLENGE",
	2: "CHALLENGE_RESPONSE",
	3: "PAYLOAD",
	4: "FAIL",
}
var Action_value = map[string]int32{
	"INIT":               0,
	"CHALLENGE":          1,
	"CHALLENGE_RESPONSE": 2,
	"PAYLOAD":            3,
	"FAIL":               4,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ConfigRequest struct {
	Repo          string    `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	File          string    `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	ChallengeType Challenge `protobuf:"varint,3,opt,name=challenge_type,json=challengeType,enum=Challenge" json:"challenge_type,omitempty"`
	Nonce         string    `protobuf:"bytes,4,opt,name=nonce" json:"nonce,omitempty"`
	Action        Action    `protobuf:"varint,5,opt,name=action,enum=Action" json:"action,omitempty"`
	Value         []byte    `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ConfigRequest) Reset()                    { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()               {}
func (*ConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConfigRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *ConfigRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ConfigRequest) GetChallengeType() Challenge {
	if m != nil {
		return m.ChallengeType
	}
	return Challenge_TOKEN
}

func (m *ConfigRequest) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *ConfigRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INIT
}

func (m *ConfigRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ConfigResponse struct {
	Repo          string    `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	File          string    `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	ChallengeType Challenge `protobuf:"varint,3,opt,name=challenge_type,json=challengeType,enum=Challenge" json:"challenge_type,omitempty"`
	Nonce         string    `protobuf:"bytes,4,opt,name=nonce" json:"nonce,omitempty"`
	Action        Action    `protobuf:"varint,5,opt,name=action,enum=Action" json:"action,omitempty"`
	Key           []byte    `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte    `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ConfigResponse) Reset()                    { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()               {}
func (*ConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConfigResponse) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *ConfigResponse) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ConfigResponse) GetChallengeType() Challenge {
	if m != nil {
		return m.ChallengeType
	}
	return Challenge_TOKEN
}

func (m *ConfigResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *ConfigResponse) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INIT
}

func (m *ConfigResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ConfigResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigRequest)(nil), "ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "ConfigResponse")
	proto.RegisterEnum("Challenge", Challenge_name, Challenge_value)
	proto.RegisterEnum("Action", Action_name, Action_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xd1, 0x4e, 0xf2, 0x40,
	0x10, 0x85, 0x59, 0x28, 0xe5, 0xef, 0xfc, 0xd2, 0x6c, 0x26, 0xc6, 0xec, 0x9d, 0x84, 0x2b, 0xc2,
	0x05, 0x46, 0x7d, 0x82, 0x06, 0x2b, 0x12, 0x6a, 0x21, 0x5b, 0x12, 0xe3, 0x15, 0xc1, 0x66, 0x40,
	0x62, 0xb3, 0x5b, 0xa1, 0x98, 0xf0, 0x64, 0xbe, 0x83, 0x4f, 0x65, 0x76, 0x0b, 0xd5, 0x47, 0xf0,
	0xee, 0x3b, 0x27, 0x99, 0x33, 0x67, 0x92, 0x01, 0x3f, 0xdf, 0xea, 0x42, 0xa7, 0x3a, 0x1b, 0x58,
	0xe8, 0x7e, 0x32, 0x68, 0x0f, 0xb5, 0x5a, 0x6d, 0xd6, 0x92, 0xde, 0xf7, 0xb4, 0x2b, 0x10, 0xc1,
	0xd9, 0x52, 0xae, 0x05, 0xeb, 0xb0, 0x9e, 0x27, 0x2d, 0x1b, 0x6f, 0xb5, 0xc9, 0x48, 0xd4, 0x4b,
	0xcf, 0x30, 0x5e, 0x83, 0x9f, 0xbe, 0x2e, 0xb3, 0x8c, 0xd4, 0x9a, 0x16, 0xc5, 0x21, 0x27, 0xd1,
	0xe8, 0xb0, 0x9e, 0x7f, 0x03, 0x83, 0xca, 0x96, 0xed, 0x0a, 0xe7, 0x87, 0x9c, 0xf0, 0x1c, 0x9a,
	0x4a, 0xab, 0x94, 0x84, 0x63, 0x73, 0x4a, 0x81, 0x97, 0xe0, 0x2e, 0xd3, 0x62, 0xa3, 0x95, 0x68,
	0xda, 0x80, 0xd6, 0xa0, 0x94, 0xf2, 0x68, 0x9b, 0xb1, 0x8f, 0x65, 0xb6, 0x27, 0xe1, 0x76, 0x58,
	0xef, 0x4c, 0x96, 0xa2, 0xfb, 0xc5, 0xc0, 0x3f, 0x35, 0xdf, 0xe5, 0x5a, 0xed, 0xe8, 0x0f, 0x56,
	0xe7, 0xd0, 0x78, 0xa3, 0xc3, 0xb1, 0xb8, 0xc1, 0x9f, 0x63, 0x5a, 0xbf, 0x8e, 0xe9, 0x5f, 0x81,
	0x57, 0xed, 0x43, 0x0f, 0x9a, 0xf3, 0xe9, 0x24, 0x8c, 0x79, 0x0d, 0xff, 0x43, 0x2b, 0x78, 0x4a,
	0x16, 0x93, 0xc7, 0x84, 0x33, 0x04, 0x70, 0x47, 0x43, 0xcb, 0xf5, 0xfe, 0xec, 0xb4, 0x19, 0xff,
	0x81, 0x33, 0x8e, 0xc7, 0x73, 0x5e, 0xc3, 0x36, 0x78, 0xc3, 0x87, 0x20, 0x8a, 0xc2, 0x78, 0x14,
	0x72, 0x86, 0x17, 0x80, 0x95, 0x5c, 0xc8, 0x30, 0x99, 0x4d, 0xe3, 0x24, 0xe4, 0x75, 0x93, 0x39,
	0x0b, 0x9e, 0xa3, 0x69, 0x70, 0xc7, 0x1b, 0x66, 0xfa, 0x3e, 0x18, 0x47, 0xdc, 0x79, 0x71, 0xed,
	0x43, 0xdc, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x20, 0x14, 0x3a, 0x40, 0x22, 0x02, 0x00, 0x00,
}
